#!/bin/bash
#SBATCH --account=ctbp-common
#SBATCH --partition=ctbp-common
#SBATCH --job-name=T1111
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=24:00:00
#SBATCH --mem=4000m
#SBATCH --export=ALL
#SBATCH --mail-user=sj52@rice.edu
#SBATCH --mail-type=FAIL

export s=$HOME/opt/script/results/

date
echo "My job ran on:"
cat $PBS_NODEFILE


/scratch/xc25/rosetta_bin_linux_2018.33.60351_bundle/main/source/bin/rosetta_scripts.static.linuxgccrelease -parser:protocol  native.xml -s 3gso.pdb -overwrite -ignore_zero_occupancy false > native.log
cat native.log | grep "ResResE" > temp
mv temp native.log

let "j=0"
while read line; do
	let "j=j+1"
	sed -i "s/GKRSNTTGK/$line/" test.xml
	#/work/pw8/mc70/rosetta_bin_linux_2018.33.60351_bundle/main/source/bin/rosetta_scripts.static.linuxgccrelease -parser:protocol  test.xml -s 3gso.pdb
	/scratch/xc25/rosetta_bin_linux_2018.33.60351_bundle/main/source/bin/rosetta_scripts.static.linuxgccrelease -parser:protocol  test.xml -s 3gso.pdb -overwrite -ignore_zero_occupancy false > $j.log
	cat $j.log | grep "ResResE" > temp
	mv temp  $j.log
	mv 3gso_0001.pdb $j.pdb
	sed -i "s/$line/GKRSNTTGK/" test.xml
done < peptide
